### ISSUE TITLE
No async_trait in root

### ISSUE THREAD

**Issue by Bwahharharrr** [MrGunflame/ts3-rs#1]
As per example 
```rust
use ts3::{
    async_trait, Client,
    client::TextMessageTarget,
    event::{EventHandler, ClientEnterView}
};
```
I'm getting the error:
```rust
error[E0432]: unresolved import `ts3::async_trait
```

I'm sorry I'm a rust newb.
I also tried just adding `use async_trait::async_trait` into my `src/main.rs` with my EventHandler async but it didn't like it.

Any ideas?

**Comment by MrGunflame** [comment]
Hi,

Seems like the example is incorrect, the correct import should be `ts3::client::async_trait`. Please let me know if that solved your issue.

**Comment by MrGunflame** [comment]
`async_trait` was not the only item whose paths were changed. `0.3.3` includes a fix to the examples. I'll also leave the fixed example here in case [docs.rs](https://docs.rs/ts3/0.3.3/ts3/index.html) is not up yet:

```rust
use ts3::client::{Client, async_trait, TextMessageTarget};
use ts3::event::{EventHandler, ClientEnterView};

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
     let client = Client::new("localhost:10011").await?;

     client.use_sid(1).await?;

     // Assign a new event handler.
     client.set_event_handler(Handler);

     tokio::signal::ctrl_c().await?;
     Ok(())
}

pub struct Handler;

#[async_trait]
impl EventHandler for Handler {
    async fn cliententerview(&self, client: Client, event: ClientEnterView) {
        println!("Client {} joined!", event.client_nickname);

        // Send a private message to the client using "sendtextmessage".
         client.sendtextmessage(TextMessageTarget::Client(event.clid as usize), "Hello World!")
             .await.unwrap();
     }
}
```

**Comment by Bwahharharrr** [comment]
Hi, thanks, again sorry for being a newb about it. 
I tried the example, but I just don't get anything "fired" on that event handler. 
It works for you okay?

**Comment by MrGunflame** [comment]
In order to receive events, you need to call [servernotifyregister](https://docs.rs/ts3/latest/ts3/client/struct.Client.html#method.servernotifyregister) with the appropriate scope. For `cliententerview` that should be `server` if I remember correctly.

**Comment by Bwahharharrr** [comment]
Thanks MrGunflame for the help with the `async_trait` issue and indeed the `servernotifyregister` bit which I totally missed. 

I looked at all the rust ts libraries and yours definitely is really clean so I chose it. I'm new so I've really enjoyed reading through your code and learnt alot in the process. 
Thanks again.
