### ISSUE TITLE
Is it possible to make handler trait functions &mut self

### ISSUE THREAD

**Issue by Bwahharharrr** [MrGunflame/ts3-rs#2]
Thanks for making the types shared, I noticed `cliententerview` was returning `usize` for `event.clid` but both `clientleftview` and `textmessage` events were both returning `u64` for `event.clid` and `event.invokerid`..  

.. Anyway,
I'm inside the handler, but I want to do things, like, pass to my handler struct a hashmap, but the handler function is `&self` not `&mut self`.

Is is possible to make the handler trait functions `&mut self` ? 

I tried downloading the repo and `cargo package` locally but I was erring compile errors, `E0107` on `#[derive(Debug,Decode,Default)]` saying `^^ expected 0 generic arguments` so I'm not sure how to progress on that, as I said, very much a rust newb here.

**Comment by MrGunflame** [comment]
Hi,

>  I noticed `cliententerview` was returning `usize` for `event.clid` but both `clientleftview` and `textmessage` events were both returning u64 for `event.clid` and `event.invokerid`

A few structs currently use the incorrect integer types (mostly `u64` and `usize`). I'm currently looking into making dedicated types for IDs.

> I'm inside the handler, but I want to do things, like, pass to my handler struct a hashmap, but the handler function is &self not &mut self.

Using a shared reference is not feasible here. If you need to mutate state, you should use a `Mutex` (or similar).

> I tried downloading the repo and cargo package locally

I don't exactly know what `cargo package` does, are you just looking to use the git upstream or clone for a development version?

**Comment by Bwahharharrr** [comment]
Thanks, wrt to the `Mutex`,  I'm not sure if I'm handling the `Handler` correctly.
For example I would do..
```rust
pub struct Handler { 
  usernames: HashMap<i64,String>,
}
```
and then 
```rust
#[async_trait]
impl EventHandler for Handler { 
   async fn cliententeview(&self ...   {
      self.usernames.insert ( . .  )
   }
}
```
But obviously i'm getting this `&self` is not `&mut self` so I can't change the properties of any of the values of the handler. 

I guess I'm not sure how to go from the function inside the handler, in this case the `async fn cliententerview(...`   to using that data in a way where I can save/access/store that data given `Handler` is not mutable. 

I also tried adding a `mspc::Sender`  channel to the Handler struct but also this was not allowed. My plan was to send the data from outside the handler to another struct that was then mutable. 

Again, my apologies for being very newb on this

**Comment by MrGunflame** [comment]
You will have to wrap your data in and go though a `Mutex`:

```rust
use std::sync::Mutex;

pub struct Handler {
    usernames: Mutex<HashMap<i64, String>>,
}

#[async_trait]
impl EventHandler for Handler {
    async fn cliententerview(&self, ..) {
        let mut users = self.usernames.lock().unwrap();
        users.insert(..);
    }
}
```

**Comment by Bwahharharrr** [comment]
Great, that worked.
TBH I was very surprised that worked since the `&self` was not mutable yet adding that `sync::Mutex` seemed to allow `self.usernames` to then change. 
Thanks for the help
